# [Not Done:] The Linear Model III: Interactions

In the previous two chapters, we have introduced the linear model, and showed how we can model (i) both continuous and categorical independent variables (including the idea of dummy coding), as well as (ii) both continuous and categorical dependent variables, the latter of which requires a generalization of the linear model, and we covered one such model, logistic regression. 

In this chapter we will build on these by introducing the idea of statistical moderation, and how we can model this by adding **interactions** into a linear model.

The learning objectives for this chapter are:

- Readers should be able to understand the concept of moderation.
- Readers should be able to interpret basic interactions in a regression model, including group-dependent slopes, simple effects vs. main effects.





```{r lmiii-setup, echo=T, warning=F, message=F}
# Load the libraries we'll use in this chapter
library(tidyverse)
```







- Cover interpretation of interactions. 
- Concept of moderation
- simple effect vs main effect

